INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Cute animals', 'Adorable');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Majestic landscapes', 'Breathtaking');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Delicious cuisine', 'Mouthwatering');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Extreme sports', 'Thrilling');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Modern architecture', 'Striking');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Abstract art', 'Expressive');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Romantic moments', 'Intimate');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Exciting board games', 'Competitive');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Powerful automobiles', 'Fast');
INSERT INTO `categories` (`id`, `description`, `name`) VALUES (NULL, 'Elegant attire', 'Sophisticated');